version: "3.8"

services:
  traefik:
    container_name: chat-base-traefik
    image: traefik:v2.9
    command:
      - "--providers.file.filename=./traefik/dynamic.yml"
      - "--providers.file.watch=true"

      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.server.address=:5000"
      - "--entrypoints.api.address=:${API_PORT}"
      
      - "--certificatesResolvers.letsencrypt.acme.email=letsencrypt@lazycore.io"
      - "--certificatesResolvers.letsencrypt.acme.storage=/traefik/acme.json"
      - "--certificatesResolvers.letsencrypt.acme.httpChallenge.entryPoint=web"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
      - "5000:5000"
      - "5001:5001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/traefik/traefik.yml:ro
      - ./traefik/dynamic.yml:/traefik/dynamic.yml:ro
      - ./traefik/acme.json:/traefik/acme.json
    networks:
      - chat-base

  app:
    container_name: chat-base-app
    build: ./app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vite.rule=Host(`${HOST_IP}`) && PathPrefix(`/`)"
      # - "traefik.http.routers.vite.rule=HostRegexp(`{host:.+}`) && PathPrefix(`/`)"
      - "traefik.http.routers.vite.entrypoints=web"
      - "traefik.http.services.vite.loadbalancer.server.port=${APP_PORT}"
    networks:
      - chat-base

  api:
    container_name: chat-base-api
    build: ./api
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`${HOST_IP}`) && PathPrefix(`/`)"
      - "traefik.http.routers.api.entrypoints=api"
      - "traefik.http.services.api.loadbalancer.server.port=${API_PORT}"
    networks:
      - chat-base

  server:
    container_name: chat-base-server
    build: ./server
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.server.rule=Host(`${HOST_IP}`) && PathPrefix(`/`)"
      - "traefik.http.routers.server.entrypoints=server"
      - "traefik.http.services.server.loadbalancer.server.port=5000"
    environment:
      - JWT_SECRET=${JWT_SECRET}

      - MONGO_DB_USERNAME=${MONGO_DB_USERNAME}
      - MONGO_DB_PASSWORD=${MONGO_DB_PASSWORD}
      - MONGO_DB_NAME=${MONGO_DB_NAME}

      - HOST_IP=${HOST_IP}
      - APP_DOMAIN=${APP_DOMAIN}
      - API_DOMAIN=${API_DOMAIN}
      - APP_PORT=${APP_PORT}
      - API_PORT=${API_PORT}
    volumes:
      - ./traefik/dynamic.yml:/traefik/dynamic.yml
      - ./.env:/env/.env
    networks:
      - chat-base

  mongodb:
    container_name: chat-base-mongodb
    image: mongo:5.0
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_DB_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - chat-base

  cassandra:
    container_name: chat-base-cassandra
    image: cassandra:latest
    ports:
      - "9042:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra
    environment:
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M

volumes:
  mongodb_data:
  cassandra_data:

networks:
  chat-base:
    driver: bridge